### ISSUE TITLE
dm_convert can not find my TIF-images (stack)

### ISSUE THREAD

**Issue by samuel424** [RI-imaging/qpformat#7]
Hello!
I have taken interferometric images with phasics SID4BIO camera using NIKONs NIS-elements software. I have successfully converted the interferometric  images into phase and intensity images using MATLAB. I have then stacked the phase and intensity images using python , into a similar format as the PHASICS "SID PHA" format. However, drymass/qpformat can not seem to find my images with the command dm_convert.

**This the code i use to convert my data to a TIF-stack:**

```
from skimage import data, io, filters
from skimage.transform import resize
import numpy as np
import tifffile

#Read Intensity and Pahse tif images
inte = io.imread('Intensity.tif')
inte = resize(inte, (800, 864))
print(inte.shape)
print(inte.dtype)


phas = io.imread('Phase.tif')
phas = resize(phas, (800, 864))
print(phas.shape)
print(phas.dtype)


#Normalize with max of image
maxinte= np.max(inte)
maxphas=np.max(phas)

inte=inte/maxinte
phas=phas/maxphas

print('max Intensity :',np.max(inte))
print('max Phase :',np.max(phas))


#Create stack of Intensity and Phase data
stack=np.array([inte,phas,phas])
print(stack.shape)
print(stack.dtype)


#save images, in two formats.
tifffile.imwrite('sensor_data.tif',stack)

tifffile.imwrite('multi-channel_resized.tif', stack,photometric='minisblack', metadata={'axes': 'IYX'})

```

**And this is the error in the anaconda prompt:**

```
(Master) C:\Users\samue\Documents\Master-Thesis\Pyhton\Test\160922-Bild-strack>dm_convert test
DryMass version 0.12.0
Traceback (most recent call last):
  File "C:\Users\samue\anaconda3\envs\Master\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\samue\anaconda3\envs\Master\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\samue\anaconda3\envs\Master\Scripts\dm_convert.exe\__main__.py", line 7, in <module>
  File "C:\Users\samue\anaconda3\envs\Master\lib\site-packages\drymass\cli\converting.py", line 15, in cli_convert
    path_in, path_out = dialog.main(path=path,
  File "C:\Users\samue\anaconda3\envs\Master\lib\site-packages\drymass\cli\dialog.py", line 110, in main
    ds = qpformat.load_data(path_in)
  File "C:\Users\samue\anaconda3\envs\Master\lib\site-packages\qpformat\core.py", line 73, in load_data
    fmt = guess_format(path)
  File "C:\Users\samue\anaconda3\envs\Master\lib\site-packages\qpformat\core.py", line 13, in guess_format
    if fmt.verify(path):
  File "C:\Users\samue\anaconda3\envs\Master\lib\site-packages\qpformat\file_formats\fmts_ready\series_phase_phasics_tif_zip.py", line 85, in verify
    zf = zipfile.ZipFile(path)
  File "C:\Users\samue\anaconda3\envs\Master\lib\zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\samue\\Documents\\Master-Thesis\\Pyhton\\Test\\160922-Bild-strack\\test'
```

**Comment by paulmueller** [comment]
Hey,

the Tif-Stack file format only supports original data from phasics (with the metadata and phase as optical path length in nanometers instead of radians). I believe it would be hard in general to implement this properly.

Since you already have access to the raw phase and intensity data, I would suggest to use qpimage and store your data in the qpimage file format (https://qpimage.readthedocs.io/en/stable/sec_userapi.html#storing-qpimage-data-on-disk). If the qpimage docs are not clear enough, I would happily expand them  with examples for your use case.

I am not sure where the `PermissionError` comes from. It might be Windows-related (I am coding on Linux and might not be aware of some restrictions here). I have encountered it before, so there might be a simple fix already somewhere.

Also note that there is qpretrieve (https://github.com/RI-imaging/qpretrieve), which you can also use to retrieve the phase from your raw SID4Bio images (what you did in Matlab already). DryMass supports this as well...

**Comment by samuel424** [comment]
Hello!

Thank you for message. Sorry for the very late reply, I’m going to attempt to use qpretrieve for the phase extraction in python.
I’m just not very familiar with python. However, I assume something like this would work for QLSI images from PHASICS?

from dataclasses import dataclass
import matplotlib.pylab as plt
import numpy as np
import qpretrieve
from skimage.restoration import unwrap_phase
import skimage.io as skio

data = skio.imread("SID Vibrio_B3_09 000001.TIF", plugin="tifffile")
ref = skio.imread("Ref.TIF", plugin="tifffile")

QLSI= qpretrieve.interfere.if_qlsi.QLSInterferogram(data, reference=ref)
QLSI.run_pipeline(
filter_name="smooth disk",
wavelength = 800,
qlsi_pitch_term=1.87711e-08)

phase_data = plt.imshow(QLSI.phase)
plt(phase_data)




—
Kind regards,



[cid:BF28C727-6D40-40B9-B6DF-D3DA6FDCBE79]




Email: ***@***.******@***.***>
Tel: +46707202002

On 21 Sep 2022, at 22:55, Paul Müller ***@***.******@***.***>> wrote:



Hey,

the Tif-Stack file format only supports original data from phasics (with the metadata and phase as optical path length in nanometers instead of radians). I believe it would be hard in general to implement this properly.

Since you already have access to the raw phase and intensity data, I would suggest to use qpimage and store your data in the qpimage file format (https://qpimage.readthedocs.io/en/stable/sec_userapi.html#storing-qpimage-data-on-disk). If the qpimage docs are not clear enough, I would happily expand them with examples for your use case.

I am not sure where the PermissionError comes from. It might be Windows-related (I am coding on Linux and might not be aware of some restrictions here). I have encountered it before, so there might be a simple fix already somewhere.

Also note that there is qpretrieve (https://github.com/RI-imaging/qpretrieve), which you can also use to retrieve the phase from your raw SID4Bio images (what you did in Matlab already). DryMass supports this as well...

**Comment by paulmueller** [comment]
Yes, something like this would work. But please take a look at the docs for qpretrieve:

- https://qpretrieve.readthedocs.io/en/stable/sec_code_reference.html#module-qpretrieve.interfere.if_qlsi
- https://qpretrieve.readthedocs.io/en/stable/sec_code_reference.html#qpretrieve.interfere.if_qlsi.QLSInterferogram.default_pipeline_kws

E.g. you have to get the units right for wavelength [m].

Cheers

**Comment by samuel424** [comment]
Hi Paul!

Thank you! I was also wondering regarding the “qlsi_pitch_term” for the parameters on this page : https://qpretrieve.readthedocs.io/en/stable/sec_code_reference.html
We are using the SID4 sC8 camera at the lab that I’m writing my thesis in. Do you believe that this is the same value as the SID4BIO camera you give on the website?

—
Kind regards,



[cid:BF28C727-6D40-40B9-B6DF-D3DA6FDCBE79]




Email: ***@***.******@***.***>
Tel: +46707202002

On 4 Oct 2022, at 14:35, Paul Müller ***@***.******@***.***>> wrote:



Yes, something like this would work. But please take a look at the docs for qpretrieve:

  *   https://qpretrieve.readthedocs.io/en/stable/sec_code_reference.html#module-qpretrieve.interfere.if_qlsi
  *   https://qpretrieve.readthedocs.io/en/stable/sec_code_reference.html#qpretrieve.interfere.if_qlsi.QLSInterferogram.default_pipeline_kws

E.g. you have to get the units right for wavelength [m].

Cheers

**Comment by paulmueller** [comment]
Hi, it's most-likely not the same value. But if you had original raw and analyzed data from the phasics software, it would be possible to extract this number...

**Comment by samuel424** [comment]
Okay!
Thank you! 😊

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: Paul ***@***.***>
Skickat: den 8 oktober 2022 01:11
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [RI-imaging/qpformat] dm_convert can not find my TIF-images (stack) (Issue #7)


Hi, it's most-likely not the same value. But if you had original raw and analyzed data from the phasics software, it would be possible to extract this number...
